services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
